name: Deploy ReDoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Assuming you have a requirements.txt

      - name: Generate OpenAPI spec
        run: uvicorn src.main:app --app-dir src --openapi-json-path openapi.json

      - name: Build ReDoc HTML
        run: |
          mkdir -p docs
          curl -o docs/redoc.html "https://cdn.redoc.ly/redoc/latest/redoc.min.js"
          echo "<redoc spec-url='./openapi.json'></redoc>" > docs/index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: docs