name: Deploy API Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs mkdocs-material

      - name: Generate OpenAPI Docs
        run: |
          mkdir -p docs
          python -c "from fastapi.openapi.utils import get_openapi; from src.main import app; import json; open('docs/openapi.json', 'w').write(json.dumps(get_openapi(title='API Docs', version='1.0.0', routes=app.routes), indent=2))"

      - name: Create MkDocs Config
        run: |
          echo "site_name: py-ytmusic-api docs" >> mkdocs.yml
          echo "site_url: https://ponlponl123.github.io/py-ytmusic-api" >> mkdocs.yml
          echo "repo_url: https://github.com/Ponlponl123/py-ytmusic-api" >> mkdocs.yml
          echo "theme:" >> mkdocs.yml
          echo "  name: material" >> mkdocs.yml
          echo "nav:" >> mkdocs.yml
          echo "  - API Reference: openapi.json" >> mkdocs.yml

      - name: Build Docs
        run: |
          mkdocs build
          mkdocs gh-deploy

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v4
